### PR TITLE
add tests_bucklescript/operations to sources and start fixing compiler errors

### PR DESCRIPTION
**Pull request by johnhaley81**
This is the start of getting the graphql queries in `tests_bucklescript/operations` to be able to be compiled. Currently, 7 of the tests do not output code that will compile for various reasons. I've gone ahead a fixed 1 but the others aren't working still.

Right now I added the `operations` folder into the `sources` in `bsconfig.json` just to help fix thing for the moment but eventually that won't be there to allow for a better snapshot DX when things change. Instead it will live in some sort integration test to ensure that things still compile. 

Things that are remaining to do:

- [x] fix `customTypes`
- [x] fix `record`
- [x] fix `subscription`
- [x] fix `union`
- [x] fix `unionPartial`
- [x] fix `variant`
- [x] remove compiling `operations` from `bsconfig.json`
- [x] write integration test to ensure that files still compile in the future

### CODE REVIEW

**Comment by johnhaley81** [comment]
Currently there are 2 blocking issues, `customTypes` is generating a bad source file where it's trying to parse a `Color` from a `DateTime` which you can see in the [source](https://github.com/johnhaley81/graphql_ppx_re/blob/add-test-ensuring-snapshot-compilation/tests_bucklescript/static_snapshots/records/operations/customTypes.re#L65-L67).

The other blocking issue is that when manually running `bsb` from a [child process](https://github.com/reasonml-community/graphql_ppx/pull/120/files#diff-146f8113fb115b3dc27a651b5ae4c45dL106) it's not including other directories with the `-I` arg. You can even try that from the CLI and it doesn't work like so:

`./node_modules/.bin/bsc -ppx "../_build/default/src/bucklescript_bin/bin.exe " -bs-suffix -I ./operations/GraphQL_PPX.re ./operations/fragmentDefinition.re`

I'm not exactly sure how else to provide linking to external modules during compilation since from what I can see in the output from `bsc.exe -help` that's the correct flag. What am I missing? (cc @bobzhang @et7f3)

**Comment by Et7f3** [comment]
-I is for **I**nterface folder. So you should give directory with .cmi

**Comment by johnhaley81** [comment]
That's giving me an error of:

```
  We've found a bug for you!
  ./operations/fragmentDefinition.re
  
  GraphQL_PPX.js not found, needed in script mode 
  
// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';
```

**Comment by Et7f3** [comment]
in operations/customTypes after runnig with ppx I see
```
let nullableColor = {
                let value = (value: Raw.t_customFields).nullableColor;
                switch (Js.toOption(value)) {
                | Some(value) =>
                  Some(
                    GraphqlHelpers.Color.parse(
                      GraphqlHelpers.Color.parse(value),
                    ),
                  )
                | None => None
                };
              }
```

the double parse seem like a bug ?

And we get:
```

  We've found a bug for you!
  (No file name)
  
  This has type:
    GraphqlHelpers.Color.t
  But somewhere wanted:
    Js.Json.t (defined as Js.Json.t)
```

**Comment by jfrolich** [comment]
> That's giving me an error of:
> 
> ```
>   We've found a bug for you!
>   ./operations/fragmentDefinition.re
>   
>   GraphQL_PPX.js not found, needed in script mode 
>   
> // Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
> 'use strict';
> ```

Yes that is expected because there is a dependency on that module (it needs the `deepMerge` function in that module for serialize). It should be in the folder.

**Comment by jfrolich** [comment]
> in operations/customTypes after runnig with ppx I see
> 
> ```
> let nullableColor = {
>                 let value = (value: Raw.t_customFields).nullableColor;
>                 switch (Js.toOption(value)) {
>                 | Some(value) =>
>                   Some(
>                     GraphqlHelpers.Color.parse(
>                       GraphqlHelpers.Color.parse(value),
>                     ),
>                   )
>                 | None => None
>                 };
>               }
> ```
> 
> the double parse seem like a bug ?
> 
> And we get:
> 
> ```
> 
>   We've found a bug for you!
>   (No file name)
>   
>   This has type:
>     GraphqlHelpers.Color.t
>   But somewhere wanted:
>     Js.Json.t (defined as Js.Json.t)
> ```

That doesn't look good! :)

**Comment by Et7f3** [comment]
I have spotted where the double is added. @jfrolich Where I should commit ?

**Comment by jfrolich** [comment]
> I have spotted where the double is added. @jfrolich Where I should commit ?

Can you make a PR with 1.0 as a base?

**Comment by johnhaley81** [comment]
@jfrolich I was able to get the manual compiler step to work. I had to move all of the utility files into `utils` in order to make things easier to work. Everything is good except for the error in `customTypes`. Any ideas how to fix that?

**Comment by jfrolich** [comment]
Yes I fixed it

**Comment by jfrolich** [comment]
If you pull in 1.0 it should be fixed.

**Comment by johnhaley81** [comment]
@jfrolich this should be gtg now

**Comment by jfrolich** [comment]
Awesome!! There is some npm problem on Linux it looks like.

**Comment by jfrolich** [comment]
I think it would be great to do compilation tests for different ppx flags (such as records/objects)

**Comment by jfrolich** [comment]
Awesome work @johnhaley81! I dropped in with some (hopefully) improvements.

Instead of checking for empty errors, I snapshotted the JS. This also captures regressions/changes in the JS output. I have had some instances before where the generated javascript became less nice than before and only realized it when I applied the ppx on my production repo.

I added variants for objects and records as ppx switches for now (but we can add more).

@johnhaley81 @jsiebern can you provide a review/sanity check?

**Comment by johnhaley81** [comment]
@jfrolich I really like taking a snapshot of the JS output. That's a great idea! This looks good to me.

**Pull request merged**
