### PR TITLE
fix: omit double parse

### PR DESCRIPTION
**Pull request by Et7f3**
See https://github.com/reasonml-community/graphql_ppx/pull/120#issuecomment-627241933

### CODE REVIEW

**Comment by jfrolich** [comment]
Can you update the snapshot so the tests pass? Then I will merge ASAP.

**Comment by Et7f3** [comment]
Oh wait no others test are broken and they should. It isn't the right fix. Sorry for the noise.

**Comment by jfrolich** [comment]
@jsiebern somehow there is a bug that a color field is parsed twice (once with the incorrect datetime decoder). I looked through the source but couldn't find an obvious explanation why this is happening (the commit is not the correct fix). Any ideas?

**Comment by jsiebern** [comment]
Probably forgot to add an
```reason
if (!raw) {};
```
somewehre 🤔 I'll check later tonight

**Comment by jfrolich** [comment]
Ah I found it! It double encodes because it is a custom field AND it has an override with `@ppxDecoder`, this case isn't covered atm.

**Pull request merged**
