### PR TITLE
Support config from bsconfig.json

### PR DESCRIPTION
**Pull request by jsiebern**
**This PR is not ready to merge yet.**

It just serves as a first experiment that supports the default args.
Let's discuss the implementation and what possible configurations should be supported.

Example:
```json
{
    "ppx-flags": ["../_build/default/src/bucklescript_bin/bin.exe"],
    "graphql-ppx": {
        "verbose": true,
        "apollo-mode": false,
        "mode": "records | objects | legacy",
        "schema": "../graphql_schema.json",
        "ast-out": false,
        "definition": true
    }
}
```

@jfrolich mentioned global `@ppxDecoder` definitions. I suppose that could look something like this:
```json
{
  "graphql-ppx": {
    "apollo-mode": true,
    "mode": "records",
    "ppxDecoders": {
      "date": "GraphqlDecoders.Date",
      "uuid": "GraphqlDecoders.UuidToString",
      "CustomScalar": "GraphqlDecoders.CustomScalar"
    }
  }
}
```

### CODE REVIEW

**Comment by jfrolich** [comment]
Great work, love it!

Some feedback:

- It would be great to also simultaneously support ppx args for the following reasons:
  - Backwards compatibility
  - Snapshot testing is easier when flipping a cli switch
- For the key in the `bsconfig` I think I prefer "graphql". This will also allow settings to be shared between PPX's that do something with GraphQL.
- For the `ppxDecoder` can we use `customFields`? (It is called `customScalars` in Relay but we support more than just scalars. Also "decoder" is outdated as we now also support serialization (at least soon :)). See also https://reason-relay-documentation.zth.now.sh/docs/custom-scalars.
- I like the "mode" setting, it eliminates some options.

**Comment by jfrolich** [comment]
For the different types of settings I think the follow precedence makes sense:

- default config
- `bsconfig.json`
- ppx args
- individual configuration inside the query

**Comment by jsiebern** [comment]
> It would be great to also simultaneously support ppx args

That already works, I didn't remove any of the args code.

> For the different types of settings I think the follow precedence

The order you have described is kept in the current implementation. Only question is, if new features like customFields should be added to the args. Could be a bit awkward to use. 

> For the key in the bsconfig I think I prefer "graphql".

Makes sense to me 👍 

> For the ppxDecoder can we use customFields

Agreed.

> I like the "mode" setting, it eliminates some options.

I'm thinking to replace the `ast-out` with a string as well, as it's more descriptive. Any thoughts / objections?

**Comment by jsiebern** [comment]
The suggested changes to the config layout are implemented.

I also added global configurable customFields to the config parsing. Let me know if you have any feedback on the point of "insertion" in `result_decoder.de`. It is still possible to override the global definition with a `@ppxDecoder` directive this way.

**Comment by jfrolich** [comment]
> The order you have described is kept in the current implementation. Only question is, if new features like customFields should be added to the args. Could be a bit awkward to use.

I agree, it's more ergonomic in a configuration file
 
> I'm thinking to replace the `ast-out` with a string as well, as it's more descriptive. Any thoughts / objections?

Yep make sense, allows us to add more options later if needed.

**Comment by jsiebern** [comment]
I have just experimented with the format `...ppx -custom-field Date Helpers.DateTime -custom-decoder Color Helpers.Color`. It lends itself well to the args parser already used with `Args.Tuple`. It's easy enough to implement, just depends if there's need for it to be available for CLI usage.

**Comment by jsiebern** [comment]
I just added it after all. It's a small change and I guess it can't hurt.

```json
{
  "ppx-flags": [
    [
      "../_build/default/src/bucklescript_bin/bin.exe",
      "-custom-field",
      "DateTime",
      "Helpers.DateTime",
      "-custom-field",
      "Color",
      "Helpers.Color"
    ]
  ],
}
```
or
`.../ppx -custom-field DateTime Helpers.DateTime -custom-field Color Helpers.Color`

**Comment by jfrolich** [comment]
Can you add final newlines to the edited files? (vscode setting: `"files.insertFinalNewline": true`). This gives better git diffs and is used in this repo.

**Comment by jfrolich** [comment]
You think this is mergable? About the using a ref, I think it's fine as long as it works (we can always refactor later).

**Comment by jsiebern** [comment]
Added the lines, sorry I missed that. I believe it is ready for merging, yes. I added nothing too complicated and it works in the tests and in my own project.

**Comment by johnhaley81** [comment]
Just came here to add a big 👍. We have been really looking forward to custom scalars that's in here!

**Comment by johnhaley81** [comment]
@jfrolich if you can cut another RC I'll pull this in and beta test it

**Comment by jfrolich** [comment]
FYI every commit is released with the commit hash on npm now, but I will make beta 7 available soon!

**Pull request merged**
