### PR TITLE
Fix the error output positions

### PR DESCRIPTION
**Pull request by jsiebern**
It worked in all of my tests so I hope I haven't overlooked anything on this. The problem was basically that the buffer location was stripped away when determining the position of the error inside the file.

### CODE REVIEW

**Comment by jfrolich** [comment]
💙💚💛💜
I wish we could somehow test the output of errors. Perhaps we can snapshot test the Bucklescript compiler output for certain errors? What do you think?

**Comment by jfrolich** [comment]
> Just thinking.. Is there a way that a positional error may span more than one line? If so it needs a little adjustment yet.

Hmm I think that might be a possibility indeed.

**Comment by jsiebern** [comment]
> Perhaps we can snapshot test the Bucklescript compiler output for certain errors? What do you think?

That's possible I believe, as the error is added to the AST. We probably need to capture the compiler formatted location by some regex. 

> Hmm I think that might be a possibility indeed.

Alright, it's an easy enough fix.

I'll look into both of those later today.

**Comment by jfrolich** [comment]
> That's possible I believe, as the error is added to the AST. We probably need to capture the compiler formatted location by some regex.


I was more thinking along the lines of literally capturing the output of the `bsc` command and snapshotting that. This also means that if there are regressions due to a change in bucklescript, it's captured in the test.

**Comment by jsiebern** [comment]
The error position for the missing fragment error is added here as well now.

I have further added a way of snapshot testing for compiler errors. The output in `missingField2.txt` is not 100% ideal yet (I believe it's 2 chars of). It's definitely good enough for now, but I'll try getting to the bottom of this as well. I'll leave the snapshot this way for now so we can proceed.

**Comment by jsiebern** [comment]
I merged this branch with `1.0` now. There was an issue with the new `ast_transforms.re` in that it would fail hard if it could not find a type in the schema. I have made the transformer skip unknown types now.

I believe this will work fine (the fact that erroneous parts of the ast do not get transformed), as the errors will be caught later in a cleaner way anyway and compilation will fail (so it doesn't actually matter which parts are transformed).

**Comment by jsiebern** [comment]
That windows check seems like a random failure, any way to re-run it other than a dummy commit?

**Comment by jfrolich** [comment]
I did a re-run.

**Comment by jfrolich** [comment]
Some errors with the test runner. LGTM. Fix potential windows issues in post.

**Pull request merged**
