### PR TITLE
Fix location of types for better editor support

### PR DESCRIPTION
**Pull request by jsiebern**
This PR addresses #96 .

First findings:
- Parsers & Serializers overwrite the location info of the types (sometimes with references to the `Raw` module types
- The spans that get passed to `Fr_named_field` as results don't include the span for the name of the field but rather it's entirety (including their selection set)
- That means that fine grained mouse over display of types for each individual field are not possible currently (at least not for nested objects)
- Argument types are not being referenced with locations in the types module at all. They get their types exclusively from the serialize module and are all the same / `Raw`

Todo:
- [x] Prevent the parsers & serializers from overwriting the type locations
- [x] Add the key location to the field information at `Fr_named_field` and `Field` in the result structure
- [x] Only attach locations to the type definitions if `raw` is `false`, in order to display qualified types
- [x] Attach type location for fragments
- [x] Attach type location for query/mutation/subscription keyword
- [x] Fix location for object input args (example: `scalarsInput.re: $arg: VariousScalarsInput!)`
- [x] Add printed type from schema to the type constraint on input args, keep the reason type on the arg itself
- [x] Attach type location for union keys (`... on Union`)
- [x] Attach type location for bsVariant keys
- [x] Attach type locations for objects / legacy (no problem, just not done yet)
- [x] Making sure that error messages in parsers / serializers are not affected by not having locations

Finished improvements in action:

Bildschirmvideo-aufnehmen-2020-05-01-um-04 13 04
Bildschirmvideo-aufnehmen-2020-05-01-um-04 13 29
Bildschirmvideo-aufnehmen-2020-05-01-um-04 12 30

### CODE REVIEW

**Comment by jfrolich** [comment]
Wow great work! And I agree with all the points. I do think however we need to add some locations to the parsers/serializers to preserve good errors (luckily we have test coverage for that now 😍).

**Comment by jsiebern** [comment]
Yep, I agree! I have preserved the locations for the `generate_error` functions in each module. I hope that covers almost all of the cases already.

**Comment by jsiebern** [comment]
Latest progress (see checked todos above):

Bildschirmvideo aufnehmen 2020-05-02 um 03 47 13

Bildschirmvideo-aufnehmen-2020-05-02-um-03 48 13

**Comment by jfrolich** [comment]
I'd love to have this in our code base!

**Comment by jsiebern** [comment]
As far as features are concerned I'm happy with this now.
There are a few things we could still do like giving the second `$arg` a type location in this example:
```graphql
  query ($arg: VariousScalarsInput!) {
    scalarsInput(arg: $arg)
  }
```

The effort to get this working is not really worth it though (and as far as I can tell I'd need to add more dummy types, which I don't really want to do).

Same goes for the `scalarsInput` in the example, we could show the printed GraphQL for that in a comment, but work / reward / clutter ratio doesn't add up here as well.

**Comment by jfrolich** [comment]
Brilliant 😍

**Pull request merged**
