### PR TITLE
feat(native): add unified definition

### PR DESCRIPTION
**Pull request by lessp**
This adds the recent changes with `.definition` to native as well. Also, hopefully, addresses some issues with dependencies on the native side!

### CODE REVIEW

**Comment by lessp** [comment]
Seems like there's an error due to a deprecation. Will have to look into at a later time!

**Comment by baransu** [comment]
There is https://github.com/baransu/graphql_ppx_re/pull/47 tracking proper setup with BuckleScript 5 and 6+ support as well as native with recent versions of OCaml. I hope I'll manage to fix Windows CI so I can merge. Then you could rebase on top of it 🙂

**Comment by jfrolich** [comment]
I also found out that all the test's `.rei` files now don't include the definition in the signature.

**Comment by lessp** [comment]
> I also found out that all the test's `.rei` files now don't include the definition in the signature.

That's for BuckleScript though, right? @jfrolich

**Comment by jfrolich** [comment]
> > I also found out that all the test's `.rei` files now don't include the definition in the signature.
> 
> That's for BuckleScript though, right? @jfrolich

Yes

**Comment by jfrolich** [comment]
By the way. In terms of clean-up for a possible v.1. I think the third parameter of the unified definition can easily be constructed from the simpler `makeVariables` function in user land. It will also save generated code, because we can just pass in makeVariables. So it will be `(query, parse, makeVariables)`, and just generate a js-array of existing variables. What do you think?

**Comment by baransu** [comment]
@jfrolich Probably a good idea. Could you create an issue for that? I'll at it to 1.0 milestone

**Comment by lessp** [comment]
Looks like all checks passed, should be ready to go whenever you feel the timing is right @baransu

**Comment by baransu** [comment]
Thank you @lessp!

**Pull request merged**
