### PR TITLE
Input object validation

### PR DESCRIPTION
**Pull request by jsiebern**
Adds input object validation in addition to arguments. This is draft only for now, I'll need to experiment and iterate for a bit yet. I will eventually port the argument validation to the abstracted method in this branch as well.

### CODE REVIEW

**Comment by jsiebern** [comment]
@jfrolich I'd appreciate it a lot if you could get this PR a shot in your project. The logic is mostly finalized, just needs some testing in the real world I think.

**Comment by jfrolich** [comment]
Hi @jsiebern, I just ran this on my codebase and it compiled flawlessly with no diffs in the produced code.

**Comment by jsiebern** [comment]
Ok, so at least no regressions. Are you composing input objects somewhere directly in the string?

**Comment by jfrolich** [comment]
> Ok, so at least no regressions. Are you composing input objects somewhere directly in the string?

No, I don't do that anywhere.

**Comment by jsiebern** [comment]
Makes sense then. Thanks for testing anyway! I'm just implementing the last edge case (object definitions inside of lists), then I'll merge it. The tests are all valid still as before.

**Pull request merged**
